# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - MachinePredctionSj

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://machinepredctionsj.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_cf8450250bb34b9594ffdcab76446ed8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6121a7c95f464b399834790b269606ce }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: machinepredctionsj.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7A948EC82C3543CEAEE6986F01C1235E}}/machinepredictionsj:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'MachinePredctionSj'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f9c0674a3fe04aac814984950bd7c58d }}
        images: 'machinepredctionsj.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cf8450250bb34b9594ffdcab76446ed8 }}/machinepredictionsj:${{ github.sha }}'
